#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

hosts=""
while read -r line
do
    (echo "$line" | grep -Eq \#CNAME$) && continue
    hosts="$hosts$line\n"
done < "/etc/hosts"

if [ "$#" -lt 1 ] || [ "$1" != "--clean" ]; then
    # For each line in /etc/cname-hosts
    while read -r line
    do
        [ -z "$line" ] && continue
        IFS=" " read first rest <<< "$line"
        ip=`nslookup $first | awk '/^Address: / { print $2 }'`
        [ -z "$ip" ] && continue
        hosts="$hosts$ip $rest #CNAME\n"
    done < "/etc/cname-hosts"
else
    echo "Cleaning /etc/hosts..."
fi

echo -e -n $hosts > /etc/hosts
